// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbmtayllfxudwfqcazgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZibXRheWxsZnh1ZHdmcWNhemd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MDExNDMsImV4cCI6MjA2NzQ3NzE0M30.oHBdFtXnf_578hntxbnXXYn1Ncxr-kRbpD8poYy-4-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// SSO-only configuration: No session persistence needed
// All authentication is handled via SSO proxy (/api/me)
// Database access is controlled by RLS policies using auth.uid()
export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: false,     // No session persistence for SSO
      autoRefreshToken: false,   // No token refresh needed
      detectSessionInUrl: false, // No URL session detection
      storage: undefined,        // No storage needed
    }
  }
);

// Made with Bob
